### ISSUE TITLE
Error in the plugin Animated Names

### ISSUE THREAD

**Issue by mmedinam1600** [GamerKing195/Thirst#15]
[14:57:05] [Server thread/INFO]: [AnimatedNames] Enabling AnimatedNames v5.16.0
[14:57:05] [Server thread/INFO]: [AnimatedNames] -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
[14:57:05] [Server thread/INFO]: [AnimatedNames] Plugin: AnimatedNames v5.16.0
[14:57:05] [Server thread/INFO]: [AnimatedNames] Framework version: 2017-01
[14:57:05] [Server thread/INFO]: [AnimatedNames] Author: Maximvdw (Maxim Van de Wynckel)
[14:57:05] [Server thread/INFO]: [AnimatedNames] Site: https://www.mvdw-software.com/
[14:57:05] [Server thread/INFO]: [AnimatedNames] -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
[14:57:05] [Server thread/INFO]: [AnimatedNames] Loading configuration ...
[14:57:05] [Server thread/INFO]: [AnimatedNames] Loading placeholders ...
[14:57:06] [Server thread/ERROR]: [AnimatedNames] java.lang.NoClassDefFoundError: com/hmmcrunchy/thirst/Thirst
	at be.maximvdw.animatednamescore.placeholders.bd.initialize(ThirstPlaceholder.java:29)
	at be.maximvdw.animatednamescore.placeholders.Placeholder.registerPlaceHolder(Placeholder.java:2256)
	at be.maximvdw.animatednamescore.placeholders.bd.<init>(ThirstPlaceholder.java:24)
	at be.maximvdw.animatednamescore.placeholders.aC.a(PlaceholderLoader.java:441)
	at be.maximvdw.animatednames.AnimatedNames.initPlaceholders(Unknown Source)
	at be.maximvdw.animatednames.AnimatedNames.loadConfiguration(Unknown Source)
	at be.maximvdw.animatednamescore.BasePlugin.initialize(Unknown Source)
	at be.maximvdw.animatednamescore.BasePlugin.onEnable(Unknown Source)
	at be.maximvdw.animatednames.AnimatedNames.onEnable(Unknown Source)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376)
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326)
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421)
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382)
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337)
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272)
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.hmmcrunchy.thirst.Thirst
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more

[14:57:06] [Server thread/INFO]: [MVdWPlaceholderAPI] Using AnimatedNames to get placeholders!
[14:57:06] [Server thread/INFO]: [AnimatedNames] Loaded 2901 of the 5751 placholders
[14:57:06] [Server thread/INFO]: [AnimatedNames] Loading Event hooks ...
[14:57:06] [Server thread/INFO]: [AnimatedNames] Loading event hook: Vanilla Death hook ...
[14:57:06] [Server thread/INFO]: [AnimatedNames] Loading event hook: Vanilla Block break hook ...
[14:57:06] [Server thread/INFO]: [AnimatedNames] Loading event hook: Vanilla Block place hook ...
[14:57:06] [Server thread/INFO]: [AnimatedNames] Loading event hook: Vanilla Create portal hook ...
[14:57:06] [Server thread/INFO]: [AnimatedNames] Loading event hook: Vanilla player join ...
[14:57:06] [Server thread/INFO]: [AnimatedNames] Loading event hook: Vanilla player rejoin ...
[14:57:06] [Server thread/INFO]: [AnimatedNames] Loading event hook: Vanilla player first join ...
[14:57:06] [Server thread/INFO]: [AnimatedNames] Loading event hook: Vanilla Combat hook ...
[14:57:06] [Server thread/INFO]: [AnimatedNames] Creating new custom effect: warning
[14:57:06] [Server thread/INFO]: [AnimatedNames] 	Lines: 2
[14:57:06] [Server thread/INFO]: [AnimatedNames] 	Arguments: 1
[14:57:06] [Server thread/INFO]: [AnimatedNames] Adding teamname group 'default' ...
[14:57:06] [Server thread/INFO]: [AnimatedNames] Name prefix , suffix for group 'default' will refresh every 100 ticks
[14:57:06] [Server thread/INFO]: [AnimatedNames] Adding teamname group 'example-admin' ...
[14:57:06] [Server thread/INFO]: [AnimatedNames] Name prefix , suffix for group 'example-admin' will refresh every 100 ticks
[14:57:06] [Server thread/INFO]: [AnimatedNames] Preparing team names for existing online players ...
[14:57:06] [Server thread/INFO]: [AnimatedNames] Loading messages ...
[14:57:06] [Server thread/INFO]: [AnimatedNames] Loading language file: lang_en
[14:57:06] [Server thread/INFO]: [AnimatedNames] Adding command 'animatednames'

**Comment by cadenkriese** [comment]
Hello, very very sorry I took this long to get back to you, apparently I fiddled with my GitHub notifications and stopped receiving notifications for Thirst. However, this issue is known but I did not realize it was for any mvdw plugin. It is something on the developer of AnimatedNames side, I've contacted him about this before and have yet to receive a response.

This error does not affect either plugin in any way and both should work as normal (to my knowledge) this should merely be regarded as 'console spam' for now. I apologize for the inconvenience and delayed response.

            ~ Gamer
