### ISSUE TITLE
Thirst..

### ISSUE THREAD

**Issue by edwardtakev** [GamerKing195/Thirst#18]
when i start the server thirst gett's this error, i am using all my plugins lattest versions, some ideas ?

Could not load 'plugins\Thirst-1.9.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/cubespace/Yamler/Config/InvalidConfigurationException
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot.jar:git-Spigot-65e8124-963b19c]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:326) ~[spigot.jar:git-Spigot-65e8124-963b19c]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [spigot.jar:git-Spigot-65e8124-963b19c]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:304) [spigot.jar:git-Spigot-65e8124-963b19c]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot.jar:git-Spigot-65e8124-963b19c]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-65e8124-963b19c]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
Caused by: java.lang.NoClassDefFoundError: net/cubespace/Yamler/Config/InvalidConfigurationException
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_141]
at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_141]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-65e8124-963b19c]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-65e8124-963b19c]
... 6 more
Caused by: java.lang.ClassNotFoundException: net.cubespace.Yamler.Config.InvalidConfigurationException
at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_141]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-65e8124-963b19c]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-65e8124-963b19c]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_141]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_141]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_141]
at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_141]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-65e8124-963b19c]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-65e8124-963b19c]
... 6 more

**Comment by cadenkriese** [comment]
This looks like a maven error, I'll try and re-push the update later tonight, sorry for the inconvenience.

**Comment by cadenkriese** [comment]
This issue should be fixed in the updated 1.9.5 jar found, [here](https://www.spigotmc.org/resources/thirst.24610/update?update=183746). Thank you for the report.
