### ISSUE TITLE
java.lang.NoClassDefFoundError for InvalidConfigurationException

### ISSUE THREAD

**Issue by TrademarkTM** [GamerKing195/Thirst#19]
In the new update I'm getting another error:
```
[10:19:04] [Server thread/ERROR]: Could not load 'plugins/Thirst 1.9.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/cubespace/Yamler/Config/InvalidConfigurationException
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:326) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:304) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoClassDefFoundError: net/cubespace/Yamler/Config/InvalidConfigurationException
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_131]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.cubespace.Yamler.Config.InvalidConfigurationException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_131]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	... 6 more
```

Version: 1.12.1
Thirst version: 1.9.5 (the updated jarfile)

Also, the jarfile is 73 kb, way less than 329 kb of the 1.9.4.

**Comment by cadenkriese** [comment]
Hello, really sorry about all these compilation errors, these should all be resolved in version 1.9.6 where the jar file size is back to normal, thank you for the report.

V1.9.6 can be found [here](https://www.spigotmc.org/resources/thirst.24610/update?update=184285).
