### ISSUE TITLE
Thirst 1.9.7 is broken

### ISSUE THREAD

**Issue by Fargus-Van-Crystal-de-Mindark** [GamerKing195/Thirst#22]
Server MC spigot 1.12

The server totally crash when a thirst status of someone change after your latest update 1.9.7
I'm obliged to remove this plugin from the server, waiting that u will able to fix this.

Thanks in advance

[16:28:51] [Server thread/WARN]: [Thirst] Task #2007 for Thirst v1.9.6 generated an exception
java.lang.StringIndexOutOfBoundsException: String index out of range: 28
    at java.lang.String.substring(String.java:1963) ~[?:1.8.0_111]
    at com.gamerking195.dev.thirst.util.UtilUpdater$1.run(UtilUpdater.java:64) ~[?:?]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-8cbfc85-202da97]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[16:28:51] [Server thread/INFO]: [Server] Server is restarting. World is being saved.

**Comment by cadenkriese** [comment]
The error you posted looks like one with the auto updater and should have no effect on your actual server. If it does have an effect when it's on the server what exactly does it do? Also currently busy with school so the time it takes for this to be fixed might be a bit longer than usual.

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
It just close the server doing a restart.
Also if I disable the autoupdater... it make everyone crash doing a restar

**Comment by cadenkriese** [comment]
Could you maybe send me your entire server log from startup to crash please.

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
I already gave to you all what I had
I dind't find anything else
And I cannot reinstall the plugin, this will make us crash another time and this will take a lot of work

**Comment by cadenkriese** [comment]
That doesn't seem like an error that would crash the entire server, I'll look into it when I can though.

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
Anyway removing thirst I don't have errors or crash... 
Tanks a lot about your entiere work

**Comment by cadenkriese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX - Server crash with updater](https://trello.com/c/T9AvpEW3/60-fix-server-crash-with-updater)

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
some news?

**Comment by cadenkriese** [comment]
Hey there super sorry for the delay, as I stated above I'm very busy at the moment, this issue should be permanently fixed in my reuploaded version of 1.9.7, found [here](https://www.spigotmc.org/resources/thirst.24610/update?update=191644), thanks for the report.
