### ISSUE TITLE
Erorr? Not sure from what.

### ISSUE THREAD

**Issue by wohahobg** [GamerKing195/Thirst#33]
11.10 12:36:16 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
11.10 12:36:16 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
11.10 12:36:16 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
11.10 12:36:16 [Server] WARN at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
11.10 12:36:16 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11.10 12:36:16 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
11.10 12:36:16 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
11.10 12:36:16 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
11.10 12:36:16 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
11.10 12:36:16 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
11.10 12:36:16 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
11.10 12:36:16 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
11.10 12:36:16 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
11.10 12:36:16 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
11.10 12:36:16 [Server] WARN at com.gamerking195.dev.thirst.command.ThirstCommand.onCommand(ThirstCommand.java:211)
11.10 12:36:16 [Server] WARN at net.cubespace.Yamler.Config.YamlConfig.reload(YamlConfig.java:147)
11.10 12:36:16 [Server] WARN at net.cubespace.Yamler.Config.YamlConfig.internalLoad(YamlConfig.java:187)
11.10 12:36:16 [Server] WARN net.cubespace.Yamler.Config.InvalidConfigurationException: Could not set field
11.10 12:36:16 [Server] ERROR [Thirst] STACKTRACE: 
11.10 12:36:16 [Server] ERROR [Thirst] 
11.10 12:36:16 [Server] ERROR [Thirst] MESSAGE: Could not set field
11.10 12:36:16 [Server] ERROR [Thirst] 
11.10 12:36:16 [Server] ERROR [Thirst] PLUGIN MESSAGE: Error occurred while reloading thirst
11.10 12:36:16 [Server] ERROR [Thirst] 
11.10 12:36:16 [Server] ERROR [Thirst] PLUGIN VERSION: Thirst V1.9.11
11.10 12:36:16 [Server] ERROR [Thirst] ============== BEGIN ERROR ==============
11.10 12:36:16 [Server] ERROR [Thirst] 
11.10 12:36:16 [Server] ERROR [Thirst] If you cannot figure out this error on your own (e.g. a config error) please copy and paste everything from here to END ERROR and post it at https://github.com/GamerKing195/Thirst/issues.
11.10 12:36:16 [Server] ERROR [Thirst] A severe error has occurred with the Thirst plugin.

**Comment by cadenkriese** [comment]
Hey there, I'm currently not actively supporting thirst, however I may be able to help you with this issue. 

When does this error occur and what does it affect / what might be causing it?
